CREATE TABLE DATA_EXPERTS_SESSIONS (
    SESSION_ID BIGINT,
    SEESION_START TIMESTAMP,
    SESSION_END TIMESTAMP,
    SESSION_DATE DATE,
    TOTAL_EVENTS_IN_SESSION INTEGER,
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    COUNTRY VARCHAR(100),
    OS VARCHAR(100),
    BROWSER VARCHAR(100),
    LOGGED_IN BOOLEAN,
    USER_ID VARCHAR(255)
)
USING ICEBERG
